In [3]:
import numpy as np

In [4]:
#Scalar arithmetic
array = np.array([1, 2, 3])

In [5]:
print(array)
print(array.shape) #Output: (3,) means The array has 3 elements. It is 1-dimensional.
print(array.ndim)
print(array.dtype)

[1 2 3]
(3,)
1
int64


In [6]:
print(array + 1)
print(array - 1)

[2 3 4]
[0 1 2]


In [7]:
print(array * 2)
print(array / 2)

[2 4 6]
[0.5 1.  1.5]


In [8]:
# For square multiplication
print(array ** 2)

[1 4 9]


For Vector arithmetics

In [9]:
# We use vectorized math function
print(np.sqrt(array))


[1.         1.41421356 1.73205081]


In [10]:
array2 = np.sqrt(array)
print(array2)
print("To round each float elements to nearest integer we use the round function")
print(np.round(array2))
print("To round up to nearest bigger integer we use the ceil function")
print(np.ceil(array2))
print("To round down to nearest smaller integer we use the floor function")
print(np.floor(array2))

[1.         1.41421356 1.73205081]
To round each float elements to nearest integer we use the round function
[1. 1. 2.]
To round up to nearest bigger integer we use the ceil function
[1. 2. 2.]
To round down to nearest smaller integer we use the floor function
[1. 1. 1.]


In [11]:
print(np.pi)     #pi value

3.141592653589793


In [12]:
radii = np.array([1, 2, 3])

In [13]:
print(np.pi * radii ** 2)               #area of circle

[ 3.14159265 12.56637061 28.27433388]


In [14]:
# Element wise arithmetic
array3 = np.array([1, 2, 3]) 
array4 = np.array([4, 5 ,6])
print(array3 + array4)
print(array3 / array4)
print(array3 ** array4)

[5 7 9]
[0.25 0.4  0.5 ]
[  1  32 729]


In [15]:
# Comparision operators
scores = np.array([91, 55, 100, 73, 82, 64])
print(scores == 100)   #returns boolean value if each element meets criteria
print(scores >= 60)
print(scores < 60)

[False False  True False False False]
[ True False  True  True  True  True]
[False  True False False False False]


In [16]:
scores[scores < 60] = 0
print(scores)

[ 91   0 100  73  82  64]
