In [1]:
#Filtering = Refers to the process of selecting elements 
#            from an array that match a given conditions
import numpy as np

In [2]:
ages = np.array([[21, 17, 19, 20, 16, 30, 18, 65],
                 [39, 22, 15, 67, 18, 19, 20, 21]])

In [4]:
teenagers = ages[ages < 18]
print(teenagers)

[17 16 15]


In [9]:
adults = ages[(ages >= 18) & (ages < 65)]            #in python logical and is 'and'
print(adults)                               #but since numpy is written in C, we use & as the logical operator

[21 19 20 30 18 39 22 18 19 20 21]


In [10]:
seniors = ages[ages >= 65]
print(seniors)

[65 67]


In [11]:
evens = ages[ages % 2 ==0]
print(evens)

[20 16 30 18 22 18 20]


In [12]:
odds = ages[ages % 2 != 0]
print(odds)

[21 17 19 65 39 15 67 19 21]


In [ ]:
#where function is used to preserve the structure/shape of the array
adults = np.where(ages >= 18, ages, 0)    #1st argument = condition, 2nd arg = array, 3rd arg is a fill value!!!
print(adults)

[[21  0 19 20  0 30 18 65]
 [39 22  0 67 18 19 20 21]]
