In [1]:
import numpy as np

In [ ]:
# we need random numbers for simulation? This is the method to generate them.
rng = np.random.default_rng()       #rng = random number generator
                                    #Note: We must setup a random number generator

random numbers when rolling a dice

In [22]:
print(rng.integers(1, 7))   #(1, 7) is the range from 1 to less then 7 
#We get random values as if we rolled a dice

3


In [24]:
print(rng.integers(low = 1, high = 101))  # for better readibility

8


In [25]:
print(rng.integers(low = 1, high = 101, size = 6))
#We get 6 probable numbers between 1 and 100

[39 45  5 82 42 75]


In [36]:
# If I need to store them in a 2d array, I write
print(rng.integers(low = 1, high = 101, size = (3, 3)))

[[ 9  3 87]
 [76 84 54]
 [82 33 46]]


In [38]:
rng = np.random.default_rng(seed = 1)                    #seed is used if we have to reproduce a number
print(rng.integers(low = 1, high = 101, size = (3, 3))) #If we run this again, we will get same result

[[48 52 76]
 [96  4 15]
 [83 95 25]]


For floating point numbers

In [42]:
print(np.random.uniform(low = -1, high = 1, size = (3, 2)))

[[-0.13778043  0.93098834]
 [-0.41902533  0.66385882]
 [-0.94437785 -0.30233274]]


In [51]:
np.random.seed(seed = 1)
print(np.random.uniform(low = -1, high = 1, size = (3, 2)))

[[-0.16595599  0.44064899]
 [-0.99977125 -0.39533485]
 [-0.70648822 -0.81532281]]


Shuffle in array

In [53]:
rng = np.random.default_rng()
array = np.array([1, 2, 3, 4, 5])
rng.shuffle(array)
print(array)

[3 1 2 4 5]


In [63]:
# if we need a choice
fruits = np.array(['apple', 'orange', 'banana', 'coconut'])
fruits = rng.choice(fruits)
print(fruits)
#if I want to eat 3 fruits
fruits = np.array(['apple', 'orange', 'banana', 'coconut'])
fruits = rng.choice(fruits, size =(3, 3))
print(fruits)

apple
[['orange' 'orange' 'apple']
 ['banana' 'apple' 'orange']
 ['apple' 'coconut' 'coconut']]


For selecting emojis windows + ;

In [67]:
emotion = np.array(['😊', '😂', '😘', '😒', '😢'])   
emotion = rng.choice(emotion, size =(3, 3))
print(emotion)

[['😊' '😢' '😘']
 ['😂' '😒' '😊']
 ['😢' '😊' '😊']]
