In [48]:
import numpy as np

Slicing in Python is a technique used to extract a portion (or subset) of items from sequential data types like lists, strings, tuples, and arrays

In [49]:
matrix_A = np.array([[1, 2, 3, 4], 
                    [5, 6, 7, 8], 
                    [9, 10, 11, 12], 
                    [13, 14, 15, 16]])

In [50]:
#for array slicing we use subscript operator
#matrix_A[start:end:step]
print(matrix_A[0])


[1 2 3 4]


In [51]:
print(matrix_A[-1])  #array with index of -1 gives the last element
print(matrix_A[2:4])#from 2nd row to 4th row, do note that 4th row is exclusive meaning upto 4 and not 4

[13 14 15 16]
[[ 9 10 11 12]
 [13 14 15 16]]


In [52]:
print(matrix_A[2:])  #from 2nd row to all row

[[ 9 10 11 12]
 [13 14 15 16]]


In [53]:
print(matrix_A[0: :2])     #step means counting
#in this example we are selecting from 0 to all rows, counting by 2 or only even

[[ 1  2  3  4]
 [ 9 10 11 12]]


Step 2 prints odd terms

In [54]:
print(matrix_A[0: :3]) 

[[ 1  2  3  4]
 [13 14 15 16]]


In [55]:
print(matrix_A[0:3:2])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [56]:
print(matrix_A[::2])

[[ 1  2  3  4]
 [ 9 10 11 12]]


Note: To zoom in and out in vs code use ctrl + '+' or ctrl + '-' respectively

In [57]:
print(matrix_A[::-1]) #this prints a reverse order of the array

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [58]:
print(matrix_A[::-2])

[[13 14 15 16]
 [ 5  6  7  8]]


In [59]:
#As for column selection, we need two index
print(matrix_A[:,0])  #this prints first columne

[ 1  5  9 13]


In [60]:
print(matrix_A[::2,0])

[1 9]


In [61]:
print(matrix_A[::-1,3])

[16 12  8  4]


In [62]:
print(matrix_A[0:2,0:4])

[[1 2 3 4]
 [5 6 7 8]]


In [66]:
print("Matrix A is:\n",matrix_A,"\nIts Cofactor aij when i = 1, j =1 is:\n",matrix_A[1:,1:])    

Matrix A is:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 
Its Cofactor aij when i = 1, j =1 is:
 [[ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [69]:
print(matrix_A[0:2,0:4:2])        

[[1 3]
 [5 7]]


As mentioned previously step 2 means odd terms are obtained, but how do we print even terms?

In [70]:
print(matrix_A[0:2,1::2])

[[2 4]
 [6 8]]


In above ways we print even terms, by starting the counting step from a even position or even index that is 2. So if the starting index is odd, we get odd terms and if it is even we get even terms.

In [78]:
print("Reversing the order of columne of matrix A:",print(matrix_A[::,::-1]))

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]
Reversing the order of columne of matrix A: None
